var nb1 = prompt("");
var nb2 = 7;
nb1 = parseInt(nb1);
console.log(typeof nb1);
var resultat = nb1 % nb2;
var nb3 = nb1 % nb2;
nb3 += nb2;
window.alert(resultat);
document.write(resultat);
console.log(resultat);
